---
title: "Coastwide index of Pacific hake"
author: "Kelli Johnson, Eric Ward"
format: pdf
editor: visual
---

## Data

We are going to pull data from the `surveyjoin` package. We will restrict the data to just PBS and NWFSC samples, because the AFSC occurrences are so sparse.

```{r}
remotes::install_github("DFO-NOAA-Pacific/surveyjoin", "5843afb")
remotes::install_github("pbs-assess/sdmTMB", "d3779e3")
library(surveyjoin)
library(sdmTMB)
library(tidyr)
library(dplyr)

  d <- get_data(common = "north pacific hake", regions = c("pbs", "nwfsc"), years = 2003:2023,
                surveys = c("NWFSC.Combo","SYN HS","SYN QCS","SYN WCHG","SYN WCVI")) |>
    dplyr::group_by(event_id) |>
    slice(1) |>
  as.data.frame()
  
  saveRDS(d, "data_for_modelling_2003_2023.rds")

```

```{r}
d <- dplyr::mutate(d, 
                   lon_mid = (lon_start + lon_end)/2,
                   lat_mid = (lat_start + lat_end)/2) |>
  dplyr::filter(!is.na(lon_mid), !is.na(lat_mid))
d <- add_utm_columns(d, ll_names = c("lon_mid","lat_mid"))

mesh <- make_mesh(d, xy_cols = c("X","Y"), cutoff=20)

mesh$mesh$n
```

```{r}
d$cpue <- d$catch_weight/d$effort
d$fyear <- as.factor(d$year)
```

```{r}
fit <- sdmTMB(cpue ~ 0 + fyear,
              spatial="on",
              spatiotemporal = "AR1",
              mesh = mesh,
              data = d,
              time = "year",
              family = delta_gamma())
saveRDS(rbind(tidy(fit), tidy(fit, "ran_pars")), "hake_case_study/tidied_pars.rds")
sanity(fit) # passes all
saveRDS(fit, "fitted_models/null.rds")
```

```{r}
grid <- rbind(surveyjoin::nwfsc_grid,
surveyjoin::dfo_synoptic_grid) |>
  dplyr::select(-survey_domain_year)
years <- unique(d$year)
# create a combination of grid and years
expanded_grid <- crossing(grid, year = years)
expanded_grid$fyear <- as.factor(expanded_grid$year)

# add UTM -- this is UTM zone 10 / 32610
expanded_grid <- add_utm_columns(expanded_grid, ll_names = c("lon","lat"), utm_crs = get_crs(d, ll_names = c("lon_mid","lat_mid")))
```

```{r}

# BC index
sub <- dplyr::filter(expanded_grid, survey!="WCBTS")
predictions <- predict(fit, newdata = sub, return_tmb_object = TRUE)
bc_index <- get_index(predictions, area = sub$area, bias_correct = TRUE)

# north of 42
sub <- dplyr::filter(expanded_grid, survey=="WCBTS", lat >= 42)
predictions <- predict(fit, newdata = sub, return_tmb_object = TRUE)
wc_north_index <- get_index(predictions, area = sub$area, bias_correct = TRUE)

# South of 42 deg
sub <- dplyr::filter(expanded_grid, survey=="WCBTS", lat < 42)
predictions <- predict(fit, newdata = sub, return_tmb_object = TRUE)
wc_south_index <- get_index(predictions, area = sub$area, bias_correct = TRUE)

sub <- dplyr::filter(expanded_grid, survey=="WCBTS")
predictions <- predict(fit, newdata = sub, return_tmb_object = TRUE)
usa_index <- get_index(predictions, area = sub$area, bias_correct = TRUE)

predictions <- predict(fit, newdata = expanded_grid, return_tmb_object = TRUE)
coastwide_index <- get_index(predictions, area = expanded_grid$area, bias_correct = TRUE)

coastwide_index$type <- "Total"
bc_index$type <- "British Columbia"
wc_north_index$type <- "West Coast USA (N of 42)"
wc_south_index$type <- "West Coast USA (S of 42)"
usa_index$type <- "West Coast of USA"

saveRDS(coastwide_index,file = "coastwide_index.rds")
saveRDS(bc_index,file = "bc_index_2003_2023.rds")
saveRDS(wc_north_index,file = "wc_north_index_2003_2023.rds")
saveRDS(wc_south_index,file = "wc_south_index_2003_2023.rds")
saveRDS(usa_index,file = "usa_index.rds")

# 

p1 <- ggplot(rbind(wc_north_index, wc_south_index, bc_index), aes(year, est, col = type, fill = type)) + 
  geom_ribbon(aes(ymin = lwr, ymax = upr), alpha=0.6, col=NA) + 
  geom_line() + 
  scale_fill_viridis_d(option="magma", begin = 0.2, end = 0.8, name = "Index") + 
  scale_color_viridis_d(option="magma", begin = 0.2, end = 0.8, name = "Index") + 
  theme_bw() + 
  ylab("Estimate") + 
  xlab("Year")
ggsave(p1, filename = "Indices_2003_2023.png", width=7, height=5)

library(readr)

url <- "https://raw.githubusercontent.com/pacific-hake/hake-assessment/master/data-tables/survey-by-country.csv"
acoustic <- read_csv(url, skip=2) # skip 2 lines, comments
acoustic <- dplyr::select(acoustic, year, total) |>
  dplyr::rename(est = total) |>
  dplyr::mutate(lwr = NA, upr = NA, survey = "Acoustic")

wctbs <- readRDS("coastwide_index.rds") |>
  dplyr::select(year, est, lwr, upr) |>
  dplyr::mutate(survey="Coastwide trawl")

# scale acoustic to be on same mean in 2003
cnst <- as.numeric(acoustic[acoustic$year==2003,"est"])
acoustic$est <- acoustic$est / cnst
acoustic$lwr <- acoustic$lwr / cnst
acoustic$upr <- acoustic$upr / cnst

cnst <- as.numeric(wctbs[wctbs$year==2003,"est"])
wctbs$est <- wctbs$est / cnst
wctbs$lwr <- wctbs$lwr / cnst
wctbs$upr <- wctbs$upr / cnst

indices <- rbind(acoustic, wctbs)

p2 <- ggplot(dplyr::filter(indices,year>=2003), aes(year, est, group=survey)) + 
  geom_ribbon(aes(ymin=lwr,ymax=upr, fill = survey), alpha=0.3) + 
  geom_line(aes(col = survey),alpha=0.6) +
  geom_point(aes(col=survey),alpha=0.6, size=2) + 
  xlab("Year") + ylab("Scaled estimate") + 
  scale_color_viridis_d(begin=0.2, end=0.85) + 
  scale_fill_viridis_d(begin=0.2, end=0.85) + 
  theme_bw()

ggsave("hake_case_study/trawl_acoustic_comparison.png")

library(cowplot)
p3 <- plot_grid(p1, p2, ncol = 1, align = "v")

ggsave(p3, filename="hake_case_study/combined_plot.png")
```
